# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - node-mysql-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_59776ca555c94b08ad0796bb69d01d75 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_404dd686d7124e48ab1d9ff21665b2e9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_59776ca555c94b08ad0796bb69d01d75 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'node-mysql-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ce882b6939614296a5587c6e6d84e845 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_59776ca555c94b08ad0796bb69d01d75 }}/appsvc/staticsite:${{ github.sha }}'